# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testingGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 371)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.modelDirectoryBtn = QtWidgets.QToolButton(self.centralwidget)
        self.modelDirectoryBtn.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.modelDirectoryBtn.setObjectName("modelDirectoryBtn")
        self.labelDirectoryBtn = QtWidgets.QToolButton(self.centralwidget)
        self.labelDirectoryBtn.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.labelDirectoryBtn.setObjectName("labelDirectoryBtn")
        self.modelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.modelLineEdit.setGeometry(QtCore.QRect(190, 10, 611, 20))
        self.modelLineEdit.setObjectName("modelLineEdit")
        self.labelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.labelLineEdit.setGeometry(QtCore.QRect(190, 40, 611, 20))
        self.labelLineEdit.setObjectName("labelLineEdit")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 70, 250, 250))
        self.graphicsView.setObjectName("graphicsView")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(270, 80, 521, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
                                       "    \n"
                                       "    color: rgb(76, 32, 255);\n"
                                       "    border-style: none;\n"
                                       "    border-radius: 10px;\n"
                                       "    text-align: center;\n"
                                       "}\n"
                                       "\n"
                                       "QProgressBar::chunk {\n"
                                       "    border-radius: 10px;\n"
                                       "    background-color: qlineargradient(spread:pad, x1:0.00568182, y1:0.517, x2:1, y2:0.528, stop:0 rgba(0, 0, 100, 255), stop:1 rgba(0, 85, 255, 255));\n"
                                       "}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.predictBtn = QtWidgets.QPushButton(self.centralwidget)
        self.predictBtn.setGeometry(QtCore.QRect(100, 40, 75, 23))
        self.predictBtn.setObjectName("predictBtn")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(270, 120, 521, 23))
        self.progressBar_2.setStyleSheet("QProgressBar {\n"
                                         "    \n"
                                         "    color: rgb(76, 32, 255);\n"
                                         "    border-style: none;\n"
                                         "    border-radius: 10px;\n"
                                         "    text-align: center;\n"
                                         "}\n"
                                         "\n"
                                         "QProgressBar::chunk {\n"
                                         "    border-radius: 10px;\n"
                                         "    background-color: qlineargradient(spread:pad, x1:0.00568182, y1:0.517, x2:1, y2:0.528, stop:0 rgba(0, 0, 100, 255), stop:1 rgba(0, 85, 255, 255));\n"
                                         "}")
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_3.setGeometry(QtCore.QRect(270, 160, 521, 23))
        self.progressBar_3.setStyleSheet("QProgressBar {\n"
                                         "    \n"
                                         "    color: rgb(76, 32, 255);\n"
                                         "    border-style: none;\n"
                                         "    border-radius: 10px;\n"
                                         "    text-align: center;\n"
                                         "}\n"
                                         "\n"
                                         "QProgressBar::chunk {\n"
                                         "    border-radius: 10px;\n"
                                         "    background-color: qlineargradient(spread:pad, x1:0.00568182, y1:0.517, x2:1, y2:0.528, stop:0 rgba(0, 0, 100, 255), stop:1 rgba(0, 85, 255, 255));\n"
                                         "}")
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_4.setGeometry(QtCore.QRect(270, 200, 521, 23))
        self.progressBar_4.setStyleSheet("QProgressBar {\n"
                                         "    \n"
                                         "    color: rgb(76, 32, 255);\n"
                                         "    border-style: none;\n"
                                         "    border-radius: 10px;\n"
                                         "    text-align: center;\n"
                                         "}\n"
                                         "\n"
                                         "QProgressBar::chunk {\n"
                                         "    border-radius: 10px;\n"
                                         "    background-color: qlineargradient(spread:pad, x1:0.00568182, y1:0.517, x2:1, y2:0.528, stop:0 rgba(0, 0, 100, 255), stop:1 rgba(0, 85, 255, 255));\n"
                                         "}")
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_5.setGeometry(QtCore.QRect(270, 240, 521, 23))
        self.progressBar_5.setStyleSheet("QProgressBar {\n"
                                         "    \n"
                                         "    color: rgb(76, 32, 255);\n"
                                         "    border-style: none;\n"
                                         "    border-radius: 10px;\n"
                                         "    text-align: center;\n"
                                         "}\n"
                                         "\n"
                                         "QProgressBar::chunk {\n"
                                         "    border-radius: 10px;\n"
                                         "    background-color: qlineargradient(spread:pad, x1:0.00568182, y1:0.517, x2:1, y2:0.528, stop:0 rgba(0, 0, 100, 255), stop:1 rgba(0, 85, 255, 255));\n"
                                         "}")
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setObjectName("progressBar_5")
        self.progressBar_6 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_6.setGeometry(QtCore.QRect(270, 280, 521, 23))
        self.progressBar_6.setStyleSheet("QProgressBar {\n"
                                         "    \n"
                                         "    color: rgb(76, 32, 255);\n"
                                         "    border-style: none;\n"
                                         "    border-radius: 10px;\n"
                                         "    text-align: center;\n"
                                         "}\n"
                                         "\n"
                                         "QProgressBar::chunk {\n"
                                         "    border-radius: 10px;\n"
                                         "    background-color: qlineargradient(spread:pad, x1:0.00568182, y1:0.517, x2:1, y2:0.528, stop:0 rgba(0, 0, 100, 255), stop:1 rgba(0, 85, 255, 255));\n"
                                         "}")
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setObjectName("progressBar_6")
        self.loadModelBtn = QtWidgets.QToolButton(self.centralwidget)
        self.loadModelBtn.setGeometry(QtCore.QRect(100, 10, 75, 23))
        self.loadModelBtn.setObjectName("loadModelBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.modelDirectoryBtn.clicked.connect(lambda: self.directory_dialog())
        self.labelDirectoryBtn.clicked.connect(lambda: self.directory_dialog_2())
        self.loadModelBtn.clicked.connect(lambda: self.loadModel())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modelDirectoryBtn.setText(_translate("MainWindow", "..."))
        self.labelDirectoryBtn.setText(_translate("MainWindow", "..."))
        self.predictBtn.setText(_translate("MainWindow", "Predict"))
        self.loadModelBtn.setText(_translate("MainWindow", "Load Model"))

    def directory_dialog(self):
        path_to_directory = QtWidgets.QFileDialog.getExistingDirectory(None, "Choose Directory")
        self.modelLineEdit.setText(path_to_directory)

    def directory_dialog_2(self):
        path_to_directory = QtWidgets.QFileDialog.getExistingDirectory(None, "Choose Directory")
        self.labelLineEdit.setText(path_to_directory)

    def loadModel(self):
       print('pp')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
